### ISSUE TITLE
Update `:action Vim*` mappings

### ISSUE THREAD

**Issue by AlexPl292** [logc/spaceidea#1]
Hi! Since 0.54 version of IdeaVim all the `:action Vim` mappings don't work anymore. Here are the details: https://youtrack.jetbrains.com/issue/VIM-1871#focus=streamItem-27-3864326.0-0

**Comment by logc** [comment]
Thanks @AlexPl292 ! Strange, I did not get notified about this issue. I just saw it now, when I was about to upgrade the config since it stopped working.
